services:
  - type: web
    name: langgraph-finance-sentiment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gloomy_dreams/main.py
    envVars:
      - key: NEWSAPI_KEY
        sync: false
    plan: free
